#!/bin/bash

YARN_INSTALL_VERSION=${YARN_INSTALL_VERSION:-v1.3.2}
NODE_INSTALL_VERSION=${NODE_INSTALL_VERSION:-v6.12.3}

# Install yarn
curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_INSTALL_VERSION

# Install nvm
curl https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
echo "source ~/.nvm/nvm.sh" >> ~/.bash_profile
source ~/.bash_profile
nvm install $NODE_INSTALL_VERSION
nvm use $NODE_INSTALL_VERSION
nvm alias default $NODE_INSTALL_VERSION

