#!/bin/bash

NODE_INSTALL_VERSION=${NODE_INSTALL_VERSION:-v4.4.7}

curl https://raw.githubusercontent.com/creationix/nvm/v0.31.4/install.sh | bash
echo "source ~/.nvm/nvm.sh" >> ~/.bash_profile
source ~/.bash_profile
nvm install $NODE_INSTALL_VERSION
nvm use $NODE_INSTALL_VERSION
nvm alias default $NODE_INSTALL_VERSION
